version: '3.8'

services:
  # mongodb:
  #   image: mongo:6.0-slim
  #   container_name: city_work_mongodb
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password123
  #     MONGO_INITDB_DATABASE: city_work
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #     - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #   networks:
  #     - city_work_network


  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: city_work_backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=mongodb://admin:password123@mongodb:27017/city_work?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=7d
    ports:
      - "3000:3000"
    # depends_on:
    #   - mongodb
    networks:
      - city_work_network
    volumes:
      - ./backend/uploads:/app/uploads

  # Frontend Web Service
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: city_work_frontend
    restart: unless-stopped
    environment:
      - EXPO_PUBLIC_API_BASE_URL=http://localhost:3000/api
      - EXPO_PUBLIC_WS_URL=ws://localhost:3000
    ports:
      - "19007:19007"
    depends_on:
      - backend
    networks:
      - city_work_network

volumes:
  mongodb_data:

networks:
  city_work_network:
    driver: bridge